[build]
  # This will be run the site build
  command = "npm run dev"
  # This is the directory is publishing to netlify's CDN
  publish = "dev"
  # functions build directory
  functions = "functions-build"